# Generated by Django 4.1.4 on 2023-01-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0003_alter_manga_date_created_alter_manga_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='views',
            new_name='views_manga',
        ),
    ]
