# Generated by Django 4.1.4 on 2023-01-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0004_rename_views_manga_views_manga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ('name_manga',), 'verbose_name_plural': 'Mangas'},
        ),
    ]
