# Generated by Django 4.1.4 on 2023-01-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0006_manga_num_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='genre',
        ),
        migrations.AddField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(blank=True, to='manga_app.genre'),
        ),
    ]
