# Generated by Django 4.1.4 on 2023-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0007_remove_manga_genre_manga_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='manga', to='manga_app.genre'),
        ),
    ]
