# Generated by Django 4.1.4 on 2023-01-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0008_alter_manga_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre', to='manga_app.genre'),
        ),
    ]
