# Generated by Django 4.1.4 on 2023-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0009_alter_manga_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='genre',
            field=models.ManyToManyField(blank=True, to='manga_app.genre'),
        ),
    ]
