# Generated by Django 4.1.4 on 2023-01-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0010_alter_manga_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ('name_manga',), 'permissions': [('can_add_manga', 'Can add manga'), ('can_delete_manga', 'Can delete manga'), ('can_edit_manga', 'Can edit manga'), ('can_view_manga', 'Can view manga')], 'verbose_name_plural': 'Mangas'},
        ),
    ]
