# Generated by Django 4.1.4 on 2023-01-17 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_app', '0013_manga_favorite_manga_manga_language_manga_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='favorite_manga',
        ),
        migrations.CreateModel(
            name='FavoriteManga',
            fields=[
                ('id_favorite', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorite_manga', models.BooleanField(blank=True, default=False, null=True)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_app.manga')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
