# Generated by Django 4.1.4 on 2023-01-18 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_app', '0014_remove_manga_favorite_manga_favoritemanga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemanga',
            options={'ordering': ('favorite_manga',), 'verbose_name_plural': 'Favorites Manga'},
        ),
        migrations.RemoveField(
            model_name='manga',
            name='review',
        ),
        migrations.CreateModel(
            name='ReviewManga',
            fields=[
                ('id_review', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_app.manga')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews Manga',
                'ordering': ('review',),
            },
        ),
    ]
