# Generated by Django 4.1.4 on 2023-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0015_alter_favoritemanga_options_remove_manga_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmanga',
            name='review',
            field=models.IntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Masterpiece')]),
        ),
    ]
