# Generated by Django 4.1.4 on 2023-01-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0016_alter_reviewmanga_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmanga',
            name='review',
            field=models.IntegerField(blank=True, choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Masterpiece')], null=True),
        ),
    ]
