# Generated by Django 4.1.4 on 2023-01-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0017_alter_reviewmanga_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
