# Generated by Django 4.1.4 on 2023-01-27 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_app', '0020_alter_manga_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusManga',
            fields=[
                ('id_status', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('not_read', 'Not read'), ('reading', 'Reading'), ('plan_to_read', 'Plan to Read'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='not_read', max_length=200, null=True)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_app.manga')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Status Manga',
                'ordering': ('manga',),
            },
        ),
    ]
