# Generated by Django 4.1.4 on 2023-01-30 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_app', '0021_statusmanga'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryManga',
            fields=[
                ('id_history', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_app.manga')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'History Mangas',
                'ordering': ('manga',),
            },
        ),
    ]
