# Generated by Django 4.1.4 on 2023-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0024_manga_update_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
