# Generated by Django 4.1.4 on 2023-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0025_alter_manga_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers_manga'),
        ),
    ]
