# Generated by Django 4.1.4 on 2023-02-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0026_alter_manga_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemanga',
            options={'ordering': ('favorite_manga',), 'permissions': [('adicionar_favoritemanga', 'Can add FavoriteManga'), ('mudar_favoritemanga', 'Can change FavoriteManga'), ('deletar_favoritemanga', 'Can delete FavoriteManga')], 'verbose_name_plural': 'Favorites Manga'},
        ),
    ]
