# Generated by Django 4.1.4 on 2023-02-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
