# Generated by Django 4.1.4 on 2023-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='users_profile_images'),
        ),
    ]
