# Generated by Django 4.1.4 on 2023-01-09 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manga_app', '0013_manga_favorite_manga_manga_language_manga_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapter_app', '0006_alter_chapter_options_alter_page_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentManga',
            fields=[
                ('id_comment', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga_app.manga')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('comment',),
                'permissions': [('can_add_comment', 'Can add comment'), ('can_delete_comment', 'Can delete comment'), ('can_edit_comment', 'Can edit comment'), ('can_view_comment', 'Can view comment')],
            },
        ),
        migrations.CreateModel(
            name='CommentChapter',
            fields=[
                ('id_comment', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chapter_app.chapter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ('comment',),
                'permissions': [('can_add_comment', 'Can add comment'), ('can_delete_comment', 'Can delete comment'), ('can_edit_comment', 'Can edit comment'), ('can_view_comment', 'Can view comment')],
            },
        ),
    ]
