# Generated by Django 4.1.4 on 2023-01-10 18:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0003_alter_commentmanga_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentchapter',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
