# Generated by Django 4.1.4 on 2023-01-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0004_alter_commentchapter_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentchapter',
            options={'ordering': ('date_created',), 'permissions': [('can_add_comment', 'Can add comment'), ('can_delete_comment', 'Can delete comment'), ('can_edit_comment', 'Can edit comment'), ('can_view_comment', 'Can view comment')], 'verbose_name_plural': 'Comments Chapters'},
        ),
    ]
