# Generated by Django 4.1.4 on 2023-01-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0005_alter_commentchapter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentchapter',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Comments Chapters'},
        ),
        migrations.AlterModelOptions(
            name='commentmanga',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Comments Manga'},
        ),
    ]
