# Generated by Django 4.1.4 on 2023-01-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0006_alter_commentchapter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentchapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_chapter', to='comment_app.commentchapter'),
        ),
        migrations.AddField(
            model_name='commentmanga',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_manga', to='comment_app.commentmanga'),
        ),
    ]
