# Generated by Django 4.1.4 on 2023-01-13 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment_app', '0007_commentchapter_parent_commentmanga_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentchapter',
            old_name='parent',
            new_name='reply_comment',
        ),
        migrations.RenameField(
            model_name='commentmanga',
            old_name='parent',
            new_name='reply_comment',
        ),
        migrations.CreateModel(
            name='ReplyCommentManga',
            fields=[
                ('id_reply_manga', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reply  Comments Manga',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ReplyCommentChapter',
            fields=[
                ('id_reply_chapter', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply', tinymce.models.HTMLField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reply  Comments Chapters',
                'ordering': ['-date_created'],
            },
        ),
    ]
