# Generated by Django 4.1.4 on 2023-01-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0013_manga_favorite_manga_manga_language_manga_review'),
        ('comment_app', '0010_remove_commentchapter_reply_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycommentmanga',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='manga_app.manga'),
        ),
    ]
