# Generated by Django 4.1.4 on 2023-01-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0011_replycommentmanga_manga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycommentmanga',
            name='manga',
        ),
    ]
