# Generated by Django 4.1.4 on 2023-01-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0012_remove_replycommentmanga_manga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycommentmanga',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replycommentmanga',
            name='user',
        ),
        migrations.AddField(
            model_name='commentmanga',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentmanga',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='comment_app.commentmanga'),
        ),
        migrations.DeleteModel(
            name='ReplyCommentChapter',
        ),
        migrations.DeleteModel(
            name='ReplyCommentManga',
        ),
    ]
