# Generated by Django 4.1.4 on 2023-01-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0013_remove_replycommentmanga_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentchapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='comment_app.commentchapter'),
        ),
    ]
