# Generated by Django 4.1.4 on 2023-01-05 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='img_chapter',
        ),
        migrations.AddField(
            model_name='image',
            name='chapter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chapter_app.chapter'),
        ),
    ]
