# Generated by Django 4.1.4 on 2023-01-05 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapter_app', '0002_remove_chapter_img_chapter_image_chapter_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Page',
        ),
    ]
