# Generated by Django 4.1.4 on 2023-01-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0003_rename_image_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='id_chapeter',
            new_name='id_chapter',
        ),
    ]
