# Generated by Django 4.1.4 on 2023-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0004_rename_id_chapeter_chapter_id_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image_chapter',
            field=models.URLField(max_length=900),
        ),
    ]
