# Generated by Django 4.1.4 on 2023-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0005_alter_page_image_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': [models.OrderBy(models.F('name_chapter'), nulls_last=True)], 'permissions': [('can_add_chapter', 'Can add chapter'), ('can_delete_chapter', 'Can delete chapter'), ('can_edit_chapter', 'Can edit chapter'), ('can_view_chapter', 'Can view chapter')], 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': [models.OrderBy(models.F('image_chapter'), nulls_last=True)], 'permissions': [('can_add_page', 'Can add page'), ('can_delete_page', 'Can delete page'), ('can_edit_page', 'Can edit page'), ('can_view_page', 'Can view page')], 'verbose_name_plural': 'Pages'},
        ),
    ]
