# Generated by Django 4.1.4 on 2023-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0006_alter_chapter_options_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
